name: Node.js CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run failing script
        run: |
          echo "This script will fail!"
          exit 1

      - name: Induce failure
        run: |
          echo "This step will fail intentionally"
          exit 2
